apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - /kube-controller-manager
    - --v=4
    - --profiling
    - --authentication-kubeconfig=/etc/kubernetes/kube-confs/kube-controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/kube-confs/kube-controller-manager.conf
    - --client-ca-file=/etc/kubernetes/pki/ca.pem
    - --requestheader-client-ca-file=/etc/kubernetes/pki/ca.pem
    - --logtostderr=true
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/kube-confs/kube-controller-manager.conf
    - --cluster-cidr={{K8S_CLUSTER_IP_CIDR}}
    - --cluster-name=kubernetes
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.pem
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca-key.pem
    - --service-account-private-key-file=/etc/kubernetes/pki/ca-key.pem
    - --controllers=*,bootstrapsigner,tokencleaner
    - --root-ca-file=/etc/kubernetes/pki/ca.pem
    - --leader-elect=true
    - --use-service-account-credentials=true
    - --node-monitor-grace-period=10s
    - --pod-eviction-timeout=10s
    - --allocate-node-cidrs=true
    - --feature-gates=RotateKubeletServerCertificate=true,TTLAfterFinished=true
    image: {{IMAGE}}
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      tcpSocket:
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 150m
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/kube-confs/kube-controller-manager.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: {{K8S_START_ROOT}}/etc/kubernetes/pki
    name: k8s-certs
  - hostPath:
      path: {{K8S_START_ROOT}}/etc/kubernetes/configs/kube-controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
status: {}