apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - /kube-scheduler
    - --v=4
    - --profiling
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/configs/kube-scheduler.conf
    - --leader-elect=true
    image: {{IMAGE}}
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      tcpSocket:
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 80m
    volumeMounts:
    - mountPath: /etc/kubernetes/configs/kube-scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: {{K8S_START_ROOT}}/etc/kubernetes/configs/kube-scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}